name: Build and Package

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "**/*.txt"
      - "**/.gitignore"
      - "**/LICENSE*"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "**/*.txt"
      - "**/.gitignore"
      - "**/LICENSE*"

jobs:
  build:
    name: Build project and package artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v7
        with:
          go-version: "1.26.5"
          check-latest: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9

      - name: Vulnerability check
        run: go tool govulncheck ./...

      - name: Run tests
        run: go test -race -coverprofile=coverage.out ./...

      - name: Check coverage
        run: go tool cover -func=coverage.out

      - name: Build project
        shell: bash
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Upload bin folder
        uses: actions/upload-artifact@v7
        with:
          name: database-backup-bin
          path: bin/
